Repository lambda-client/lambda, pull requests merged in 2022-10, with the labels that each got.

#383 HUD: Bindings Element
  src/main/kotlin/com/lambda/client/gui/hudgui/elements/client/Bindings.kt
Labels: new

#384 Removed MixinEntityLivingBase reflection hack
  src/main/java/com/lambda/EntityLivingBaseFireworkHelper.java
  src/main/java/com/lambda/mixin/entity/MixinEntityLivingBase.java
Labels: refactor

#288 Add 85km/h YPort mode to Speed
  src/main/kotlin/com/lambda/client/module/modules/combat/HoleSnap.kt
  src/main/kotlin/com/lambda/client/module/modules/combat/Surround.kt
  src/main/kotlin/com/lambda/client/module/modules/movement/Speed.kt
Labels: enhancement, requested changes
