Repository lambda-client/lambda, pull requests merged in 2022-04, with the labels that each got.

#291 Added BlockEvent to ForgeEventProcessor.kt
  src/main/kotlin/com/lambda/client/event/ForgeEventProcessor.kt
Labels: fix

#271 Pause AutoWalk when opposite movement key is pressed
  src/main/kotlin/com/lambda/client/module/modules/movement/AutoWalk.kt
Labels: enhancement

#272 Log only found and selected objects to reduce unnecessary entries in StashLogger module. (Issue #264)
  src/main/kotlin/com/lambda/client/module/modules/misc/StashLogger.kt
Labels: refactor

#281 Add ESP and full Nametag info to LogoutLogger
  src/main/kotlin/com/lambda/client/module/modules/misc/LogoutLogger.kt
  src/main/kotlin/com/lambda/client/module/modules/render/Nametags.kt
Labels: enhancement

#286 Add active potion effects HUD
  src/main/kotlin/com/lambda/client/gui/hudgui/elements/player/Effects.kt
Labels: new
