Repository lambda-client/lambda, pull requests merged in 2022-03, with the labels that each got.

#252 Cleanup and add more things to the troubleshoot command
  src/main/kotlin/com/lambda/client/command/commands/TroubleshootCommand.kt
Labels: documentation, refactor

#247 Changes to the script
  README.md
  setupWorkspace.sh
Labels: enhancement

#254 Refactor build script. Remove bloat.
  .editorconfig
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  src/main/java/com/lambda/mixin/MixinStateImplementation.java
  src/main/java/com/lambda/mixin/accessor/AccessorEntityFireworkRocket.java
  src/main/java/com/lambda/mixin/network/MixinNetworkManager.java
  src/main/java/com/lambda/mixin/player/MixinEntityPlayerSP.java
  src/main/java/com/lambda/mixin/render/MixinEntityRenderer.java
  src/main/java/com/lambda/mixin/render/MixinLayerCape.java
  src/main/java/com/lambda/mixin/render/MixinModelBiped.java
  src/main/java/com/lambda/mixin/render/MixinModelBoat.java
  src/main/java/com/lambda/mixin/render/MixinRenderLivingBase.java
  src/main/java/com/lambda/mixin/render/MixinRenderPlayer.java
  src/main/java/com/lambda/mixin/render/MixinTileEntitySignRenderer.java
  src/main/kotlin/com/lambda/client/capeapi/AbstractUUIDManager.kt
  src/main/kotlin/com/lambda/client/command/ClientCommand.kt
  src/main/kotlin/com/lambda/client/command/CommandManager.kt
  src/main/kotlin/com/lambda/client/commons/collections/CloseableList.kt
  src/main/kotlin/com/lambda/client/gui/hudgui/elements/player/InventoryViewer.kt
  src/main/kotlin/com/lambda/client/gui/rgui/InteractiveComponent.kt
  src/main/kotlin/com/lambda/client/manager/managers/KamiMojiManager.kt
  src/main/kotlin/com/lambda/client/manager/managers/NetworkManager.kt
  src/main/kotlin/com/lambda/client/mixin/extension/Render.kt
  src/main/kotlin/com/lambda/client/module/modules/combat/CrystalBasePlace.kt
  src/main/kotlin/com/lambda/client/module/modules/combat/VisualRange.kt
  src/main/kotlin/com/lambda/client/module/modules/misc/FakePlayer.kt
  src/main/kotlin/com/lambda/client/module/modules/misc/LogoutLogger.kt
  src/main/kotlin/com/lambda/client/module/modules/movement/ElytraFlight.kt
  src/main/kotlin/com/lambda/client/module/modules/movement/EntitySpeed.kt
  src/main/kotlin/com/lambda/client/module/modules/render/VoidESP.kt
  src/main/kotlin/com/lambda/client/util/TimeUtils.kt
  src/main/resources/mixins.lambda.json
Labels: refactor

#246 Packetfly changes
  src/main/kotlin/com/lambda/client/manager/managers/PacketManager.kt
  src/main/kotlin/com/lambda/client/module/modules/movement/Flight.kt
Labels: refactor
